const boxes = {
    "$3": [									
        {AFC: 7, NFC: 9, name: 'Big'}	,{AFC: 7, NFC: 3, name: 'JG'}	,{AFC: 7, NFC: 4, name: 'JT'}	,{AFC: 7, NFC: 5, name: 'U'}	,{AFC: 7, NFC: 6, name: 'TW'}	,{AFC: 7, NFC: 7, name: 'Wayne'}	,{AFC: 7, NFC: 2, name: 'JG'}	,{AFC: 7, NFC: 0, name: 'MJ'}	,{AFC: 7, NFC: 1, name: 'Carla'}	,{AFC: 7, NFC: 8, name: 'Big'}
        ,{AFC: 3, NFC: 9, name: 'Poy'}	,{AFC: 3, NFC: 3, name: 'Big'}	,{AFC: 3, NFC: 4, name: 'Mo'}	,{AFC: 3, NFC: 5, name: 'CF'}	,{AFC: 3, NFC: 6, name: 'Big'}	,{AFC: 3, NFC: 7, name: 'U'}	,{AFC: 3, NFC: 2, name: 'Lynn'}	,{AFC: 3, NFC: 0, name: 'Wayne'}	,{AFC: 3, NFC: 1, name: 'JT'}	,{AFC: 3, NFC: 8, name: 'MJ'}
        ,{AFC: 2, NFC: 9, name: 'Robbie W'}	,{AFC: 2, NFC: 3, name: 'Carolyn'}	,{AFC: 2, NFC: 4, name: 'Big'}	,{AFC: 2, NFC: 5, name: 'Mo'}	,{AFC: 2, NFC: 6, name: 'Carla'}	,{AFC: 2, NFC: 7, name: 'TW'}	,{AFC: 2, NFC: 2, name: 'ASN'}	,{AFC: 2, NFC: 0, name: 'David HT'}	,{AFC: 2, NFC: 1, name: 'CF'}	,{AFC: 2, NFC: 8, name: 'JG'}
        ,{AFC: 5, NFC: 9, name: 'Lynn'}	,{AFC: 5, NFC: 3, name: 'Hammer'}	,{AFC: 5, NFC: 4, name: 'Tracie'}	,{AFC: 5, NFC: 5, name: 'Big'}	,{AFC: 5, NFC: 6, name: 'Wo'}	,{AFC: 5, NFC: 7, name: 'Renee Stewart'}	,{AFC: 5, NFC: 2, name: 'David HT'}	,{AFC: 5, NFC: 0, name: 'U'}	,{AFC: 5, NFC: 1, name: 'MJ'}	,{AFC: 5, NFC: 8, name: 'Joe J'}
        ,{AFC: 0, NFC: 9, name: 'Joe J'}	,{AFC: 0, NFC: 3, name: 'Poy'}	,{AFC: 0, NFC: 4, name: 'James P'}	,{AFC: 0, NFC: 5, name: 'Hammer'}	,{AFC: 0, NFC: 6, name: 'Big'}	,{AFC: 0, NFC: 7, name: 'Mo'}	,{AFC: 0, NFC: 2, name: 'Wayne'}	,{AFC: 0, NFC: 0, name: 'POE'}	,{AFC: 0, NFC: 1, name: 'Carolyn'}	,{AFC: 0, NFC: 8, name: 'TW'}
        ,{AFC: 8, NFC: 9, name: 'MJ'}	,{AFC: 8, NFC: 3, name: 'Melinda'}	,{AFC: 8, NFC: 4, name: 'Jim B'}	,{AFC: 8, NFC: 5, name: 'Lynn'}	,{AFC: 8, NFC: 6, name: 'David HT'}	,{AFC: 8, NFC: 7, name: 'Big'}	,{AFC: 8, NFC: 2, name: 'Mo'}	,{AFC: 8, NFC: 0, name: 'Damien'}	,{AFC: 8, NFC: 1, name: 'Hammer'}	,{AFC: 8, NFC: 8, name: 'U'}
        ,{AFC: 4, NFC: 9, name: 'Mark MC'}	,{AFC: 4, NFC: 3, name: 'Carla'}	,{AFC: 4, NFC: 4, name: 'Renee Stewart'}	,{AFC: 4, NFC: 5, name: 'David HT'}	,{AFC: 4, NFC: 6, name: 'Jim B'}	,{AFC: 4, NFC: 7, name: 'Hammer'}	,{AFC: 4, NFC: 2, name: 'Big'}	,{AFC: 4, NFC: 0, name: 'James P'}	,{AFC: 4, NFC: 1, name: 'Tpitt'}	,{AFC: 4, NFC: 8, name: 'Carolyn'}
        ,{AFC: 6, NFC: 9, name: 'Damien'}	,{AFC: 6, NFC: 3, name: 'JG'}	,{AFC: 6, NFC: 4, name: 'David HT'}	,{AFC: 6, NFC: 5, name: 'Big'}	,{AFC: 6, NFC: 6, name: 'Damien'}	,{AFC: 6, NFC: 7, name: 'Melinda'}	,{AFC: 6, NFC: 2, name: 'Renee Stewart'}	,{AFC: 6, NFC: 0, name: 'Carla'}	,{AFC: 6, NFC: 1, name: 'TW'}	,{AFC: 6, NFC: 8, name: 'Jenna MC'}
        ,{AFC: 1, NFC: 9, name: 'Phil R'}	,{AFC: 1, NFC: 3, name: 'AjN'}	,{AFC: 1, NFC: 4, name: 'Lynn'}	,{AFC: 1, NFC: 5, name: 'MJ'}	,{AFC: 1, NFC: 6, name: 'Tpitt'}	,{AFC: 1, NFC: 7, name: 'CF'}	,{AFC: 1, NFC: 2, name: 'Jim B'}	,{AFC: 1, NFC: 0, name: 'JG'}	,{AFC: 1, NFC: 1, name: 'Big'}	,{AFC: 1, NFC: 8, name: 'Buddy'}
        ,{AFC: 9, NFC: 9, name: 'Carla'}	,{AFC: 9, NFC: 3, name: 'TW'}	,{AFC: 9, NFC: 4, name: 'Buddy'}	,{AFC: 9, NFC: 5, name: 'Carolyn'}	,{AFC: 9, NFC: 6, name: 'Roe'}	,{AFC: 9, NFC: 7, name: 'Joe J'}	,{AFC: 9, NFC: 2, name: 'Lynn'}	,{AFC: 9, NFC: 0, name: 'Robbie W'}	,{AFC: 9, NFC: 1, name: 'Jim B'}	,{AFC: 9, NFC: 8, name: 'Lynn'}
        ],									
        "$6": [									
            {AFC: 4, NFC: 2, name: 'Lynn'}	,{AFC: 4, NFC: 9, name: 'U'}	,{AFC: 4, NFC: 5, name: 'JT'}	,{AFC: 4, NFC: 4, name: 'Wayne'}	,{AFC: 4, NFC: 6, name: 'TW'}	,{AFC: 4, NFC: 1, name: 'Joe J'}	,{AFC: 4, NFC: 0, name: 'Hector'}	,{AFC: 4, NFC: 8, name: 'Robbie W'}	,{AFC: 4, NFC: 7, name: 'Carla'}	,{AFC: 4, NFC: 3, name: 'Big'}
            ,{AFC: 0, NFC: 2, name: 'MJ'}	,{AFC: 0, NFC: 9, name: 'Carla'}	,{AFC: 0, NFC: 5, name: 'James P'}	,{AFC: 0, NFC: 4, name: 'U'}	,{AFC: 0, NFC: 6, name: 'AIN'}	,{AFC: 0, NFC: 1, name: 'POE'}	,{AFC: 0, NFC: 0, name: 'Tracie'}	,{AFC: 0, NFC: 8, name: 'TW'}	,{AFC: 0, NFC: 7, name: 'Big'}	,{AFC: 0, NFC: 3, name: 'Buddy'}
            ,{AFC: 8, NFC: 2, name: 'Damien'}	,{AFC: 8, NFC: 9, name: 'Ann'}	,{AFC: 8, NFC: 5, name: 'Wayne'}	,{AFC: 8, NFC: 4, name: 'MJ'}	,{AFC: 8, NFC: 6, name: 'Carla'}	,{AFC: 8, NFC: 1, name: 'Carolyn'}	,{AFC: 8, NFC: 0, name: 'U'}	,{AFC: 8, NFC: 8, name: 'Big'}	,{AFC: 8, NFC: 7, name: 'Hector'}	,{AFC: 8, NFC: 3, name: 'Lynn'}
            ,{AFC: 7, NFC: 2, name: 'David HT'}	,{AFC: 7, NFC: 9, name: 'David HT'}	,{AFC: 7, NFC: 5, name: 'Melinda'}	,{AFC: 7, NFC: 4, name: 'Hammer'}	,{AFC: 7, NFC: 6, name: 'David HT'}	,{AFC: 7, NFC: 1, name: 'JG'}	,{AFC: 7, NFC: 0, name: 'Big'}	,{AFC: 7, NFC: 8, name: 'Hector'}	,{AFC: 7, NFC: 7, name: 'Joe J'}	,{AFC: 7, NFC: 3, name: 'Lyno'}
            ,{AFC: 3, NFC: 2, name: 'Big'}	,{AFC: 3, NFC: 9, name: 'Shaggie'}	,{AFC: 3, NFC: 5, name: 'POE'}	,{AFC: 3, NFC: 4, name: 'Lynn'}	,{AFC: 3, NFC: 6, name: 'Wayne'}	,{AFC: 3, NFC: 1, name: 'Big'}	,{AFC: 3, NFC: 0, name: 'Lynn'}	,{AFC: 3, NFC: 8, name: 'Jenny MC'}	,{AFC: 3, NFC: 7, name: 'TW'}	,{AFC: 3, NFC: 3, name: 'David HT'}
            ,{AFC: 6, NFC: 2, name: 'Phil R'}	,{AFC: 6, NFC: 9, name: 'JT'}	,{AFC: 6, NFC: 5, name: 'Hammer'}	,{AFC: 6, NFC: 4, name: 'Shaggie'}	,{AFC: 6, NFC: 6, name: 'Big'}	,{AFC: 6, NFC: 1, name: 'Mo'}	,{AFC: 6, NFC: 0, name: 'Hammer'}	,{AFC: 6, NFC: 8, name: 'Renee Stewart'}	,{AFC: 6, NFC: 7, name: 'POE'}	,{AFC: 6, NFC: 3, name: 'CF'}
            ,{AFC: 1, NFC: 2, name: 'Joe J'}	,{AFC: 1, NFC: 9, name: 'JG'}	,{AFC: 1, NFC: 5, name: 'Carla'}	,{AFC: 1, NFC: 4, name: 'Big'}	,{AFC: 1, NFC: 6, name: 'Hector'}	,{AFC: 1, NFC: 1, name: 'Jim B'}	,{AFC: 1, NFC: 0, name: 'Mo'}	,{AFC: 1, NFC: 8, name: 'David HT'}	,{AFC: 1, NFC: 7, name: 'James P'}	,{AFC: 1, NFC: 3, name: 'Carolyn'}
            ,{AFC: 2, NFC: 2, name: 'SWO'}	,{AFC: 2, NFC: 9, name: 'Big'}	,{AFC: 2, NFC: 5, name: 'Big'}	,{AFC: 2, NFC: 4, name: 'Renee Stewart'}	,{AFC: 2, NFC: 6, name: 'Hammer'}	,{AFC: 2, NFC: 1, name: 'Damien'}	,{AFC: 2, NFC: 0, name: 'JG'}	,{AFC: 2, NFC: 8, name: 'Mo'}	,{AFC: 2, NFC: 7, name: 'MJ'}	,{AFC: 2, NFC: 3, name: 'SWO'}
            ,{AFC: 9, NFC: 2, name: 'Buddy'}	,{AFC: 9, NFC: 9, name: 'Lynn'}	,{AFC: 9, NFC: 5, name: 'Hector'}	,{AFC: 9, NFC: 4, name: 'TW'}	,{AFC: 9, NFC: 6, name: 'Carolyn'}	,{AFC: 9, NFC: 1, name: 'MJ'}	,{AFC: 9, NFC: 0, name: 'Melinda'}	,{AFC: 9, NFC: 8, name: 'Jim B'}	,{AFC: 9, NFC: 7, name: 'Mo'}	,{AFC: 9, NFC: 3, name: 'JG'}
            ,{AFC: 5, NFC: 2, name: 'Big'}	,{AFC: 5, NFC: 9, name: 'TW'}	,{AFC: 5, NFC: 5, name: 'Mark MC'}	,{AFC: 5, NFC: 4, name: 'Carla'}	,{AFC: 5, NFC: 6, name: 'MJ'}	,{AFC: 5, NFC: 1, name: 'AIN'}	,{AFC: 5, NFC: 0, name: 'Shaggie'}	,{AFC: 5, NFC: 8, name: 'Carolyn'}	,{AFC: 5, NFC: 7, name: 'Jim B'}	,{AFC: 5, NFC: 3, name: 'Mo'}
            ]            
};